# Generated by Django 4.1.5 on 2023-01-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('accountbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=150)),
                ('memo', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('account_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountbooks.accountbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'accountbookrecords',
            },
        ),
    ]
