# Generated by Django 4.1.5 on 2023-01-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbookrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbookrecord',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
