# Generated by Django 4.1.5 on 2023-01-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
        ('accountbookrecords', '0002_alter_accountbookrecord_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbookrecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountbookrecord',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accountbookrecord',
            name='balance',
            field=models.CharField(max_length=200),
        ),
    ]
